"""Flat ICD-11 Chapter 06 diagnosis catalogue.

The visible website list uses only disorder names. The left-hand value is the
stable API token; the right-hand value is the clinician-facing label.
"""
from __future__ import annotations

from typing import List, Tuple

DiagnosisOption = Tuple[str, str]

DIAGNOSIS_OPTIONS: List[DiagnosisOption] = [
    ("disorders_of_intellectual_development", "Disorders of intellectual development"),
    ("developmental_speech_or_language_disorders", "Developmental speech or language disorders"),
    ("autism_spectrum_disorder", "Autism spectrum disorder"),
    ("developmental_learning_disorder", "Developmental learning disorder"),
    ("developmental_motor_coordination_disorder", "Developmental motor coordination disorder"),
    ("adhd", "Attention deficit hyperactivity disorder (ADHD)"),
    ("stereotyped_movement_disorder", "Stereotyped movement disorder"),
    ("schizophrenia", "Schizophrenia"),
    ("schizoaffective_disorder", "Schizoaffective disorder"),
    ("schizotypal_disorder", "Schizotypal disorder"),
    ("acute_psychosis", "Acute psychosis"),
    ("acute_transient_psychotic_disorder", "Acute and transient psychotic disorder"),
    ("delusional_disorder", "Delusional disorder"),
    ("catatonia_associated_with_another_mental_disorder", "Catatonia associated with another mental disorder"),
    ("catatonia_induced_by_substances_or_medications", "Catatonia induced by substances or medications"),
    ("secondary_catatonia", "Secondary catatonia"),
    ("major_depressive_disorder", "Major depressive disorder"),
    ("single_episode_depressive_disorder", "Single episode depressive disorder"),
    ("recurrent_depressive_disorder", "Recurrent depressive disorder"),
    ("dysthymic_disorder", "Dysthymic disorder"),
    ("mixed_depressive_and_anxiety_disorder", "Mixed depressive and anxiety disorder"),
    ("bipolar_mania", "Bipolar disorder - mania"),
    ("bipolar_depression", "Bipolar disorder - depression"),
    ("bipolar_maintenance", "Bipolar disorder - maintenance"),
    ("bipolar_type_i_disorder", "Bipolar type I disorder"),
    ("bipolar_type_ii_disorder", "Bipolar type II disorder"),
    ("cyclothymic_disorder", "Cyclothymic disorder"),
    ("generalized_anxiety_disorder", "Generalised anxiety disorder"),
    ("panic_disorder", "Panic disorder"),
    ("agoraphobia", "Agoraphobia"),
    ("specific_phobia", "Specific phobia"),
    ("social_anxiety_disorder", "Social anxiety disorder"),
    ("separation_anxiety_disorder", "Separation anxiety disorder"),
    ("selective_mutism", "Selective mutism"),
    ("ocd", "Obsessive-compulsive disorder"),
    ("body_dysmorphic_disorder", "Body dysmorphic disorder"),
    ("olfactory_reference_disorder", "Olfactory reference disorder"),
    ("hypochondriasis_health_anxiety", "Hypochondriasis (health anxiety)"),
    ("hoarding_disorder", "Hoarding disorder"),
    ("trichotillomania", "Trichotillomania (hair-pulling disorder)"),
    ("excoriation_disorder", "Excoriation (skin-picking) disorder"),
    ("ptsd", "Post-traumatic stress disorder (PTSD)"),
    ("complex_ptsd", "Complex post-traumatic stress disorder"),
    ("prolonged_grief_disorder", "Prolonged grief disorder"),
    ("adjustment_disorder", "Adjustment disorder"),
    ("reactive_attachment_disorder", "Reactive attachment disorder"),
    ("disinhibited_social_engagement_disorder", "Disinhibited social engagement disorder"),
    ("dissociative_neurological_symptom_disorder", "Dissociative neurological symptom disorder"),
    ("dissociative_amnesia", "Dissociative amnesia"),
    ("trance_disorder", "Trance disorder"),
    ("possession_trance_disorder", "Possession trance disorder"),
    ("dissociative_identity_disorder", "Dissociative identity disorder"),
    ("partial_dissociative_identity_disorder", "Partial dissociative identity disorder"),
    ("depersonalization_derealization_disorder", "Depersonalization-derealization disorder"),
    ("anorexia_nervosa", "Anorexia nervosa"),
    ("bulimia_nervosa", "Bulimia nervosa"),
    ("binge_eating_disorder", "Binge eating disorder"),
    ("avoidant_restrictive_food_intake_disorder", "Avoidant-restrictive food intake disorder (ARFID)"),
    ("pica", "Pica"),
    ("rumination_regurgitation_disorder", "Rumination-regurgitation disorder"),
    ("enuresis", "Enuresis"),
    ("encopresis", "Encopresis"),
    ("bodily_distress_disorder", "Bodily distress disorder"),
    ("body_integrity_dysphoria", "Body integrity dysphoria"),
    ("alcohol_use_disorder", "Disorders due to use of alcohol"),
    ("cannabis_use_disorder", "Disorders due to use of cannabis"),
    ("synthetic_cannabinoid_use_disorder", "Disorders due to use of synthetic cannabinoids"),
    ("opioid_use_disorder", "Disorders due to use of opioids"),
    ("sedative_hypnotic_anxiolytic_use_disorder", "Disorders due to use of sedatives, hypnotics or anxiolytics"),
    ("cocaine_use_disorder", "Disorders due to use of cocaine"),
    ("stimulant_use_disorder", "Disorders due to use of stimulants including amphetamines, methamphetamine or methcathinone"),
    ("synthetic_cathinone_use_disorder", "Disorders due to use of synthetic cathinones"),
    ("caffeine_use_disorder", "Disorders due to use of caffeine"),
    ("hallucinogen_use_disorder", "Disorders due to use of hallucinogens"),
    ("nicotine_use_disorder", "Disorders due to use of nicotine"),
    ("volatile_inhalant_use_disorder", "Disorders due to use of volatile inhalants"),
    ("mdma_or_related_drug_use_disorder", "Disorders due to use of MDMA or related drugs, including MDA"),
    ("dissociative_drug_use_disorder", "Disorders due to use of dissociative drugs including ketamine and PCP"),
    ("other_specified_psychoactive_substance_use_disorder", "Disorders due to use of other specified psychoactive substances"),
    ("gambling_disorder", "Gambling disorder"),
    ("gaming_disorder", "Gaming disorder"),
    ("pyromania", "Pyromania"),
    ("kleptomania", "Kleptomania"),
    ("compulsive_sexual_behaviour_disorder", "Compulsive sexual behaviour disorder"),
    ("intermittent_explosive_disorder", "Intermittent explosive disorder"),
    ("oppositional_defiant_disorder", "Oppositional defiant disorder"),
    ("conduct_dissocial_disorder", "Conduct-dissocial disorder"),
    ("personality_disorder", "Personality disorder (rated mild / moderate / severe)"),
    ("trait_domain_qualifiers", "Trait domain qualifiers: negative affectivity, detachment, dissociality, disinhibition, anankastia"),
    ("borderline_pattern_specifier", "Borderline pattern specifier"),
    ("exhibitionistic_disorder", "Exhibitionistic disorder"),
    ("voyeuristic_disorder", "Voyeuristic disorder"),
    ("pedophilic_disorder", "Pedophilic disorder"),
    ("coercive_sexual_sadism_disorder", "Coercive sexual sadism disorder"),
    ("frotteuristic_disorder", "Frotteuristic disorder"),
    ("other_nonconsenting_paraphilic_disorder", "Other paraphilic disorder involving non-consenting individuals"),
    ("consenting_or_solitary_paraphilic_disorder", "Paraphilic disorder involving solitary behaviour or consenting individuals"),
    ("factitious_disorder_imposed_on_self", "Factitious disorder imposed on self"),
    ("factitious_disorder_imposed_on_another", "Factitious disorder imposed on another"),
    ("delirium", "Delirium"),
    ("mild_neurocognitive_disorder", "Mild neurocognitive disorder"),
    ("amnestic_disorder", "Amnestic disorder"),
    ("dementia", "Dementia"),
    ("dementia_related_behavioural_symptoms", "Behavioural symptoms in dementia"),
    ("pregnancy_childbirth_puerperium_without_psychotic_symptoms", "Mental or behavioural disorder associated with pregnancy, childbirth or the puerperium - without psychotic symptoms"),
    ("pregnancy_childbirth_puerperium_with_psychotic_symptoms", "Mental or behavioural disorder associated with pregnancy, childbirth or the puerperium - with psychotic symptoms"),
    ("psychological_or_behavioural_factors_affecting_disorders_elsewhere", "Psychological or behavioural factors affecting disorders or diseases classified elsewhere"),
    ("secondary_psychotic_syndrome", "Secondary psychotic syndrome"),
    ("secondary_mood_syndrome", "Secondary mood syndrome"),
    ("secondary_anxiety_syndrome", "Secondary anxiety syndrome"),
    ("secondary_obsessive_compulsive_or_related_syndrome", "Secondary obsessive-compulsive or related syndrome"),
    ("secondary_dissociative_syndrome", "Secondary dissociative syndrome"),
    ("secondary_impulse_control_syndrome", "Secondary impulse control syndrome"),
    ("secondary_neurocognitive_syndrome", "Secondary neurocognitive syndrome"),
    ("secondary_personality_change", "Secondary personality change"),
    ("secondary_catatonia_syndrome", "Secondary catatonia syndrome"),
]
