"""Presentation layer: build the rich, frontend-ready API response.

The engine (``rules_engine.generate_recommendations``) returns an internal result
(scores, categories, reasons/cautions, investigations, monitoring, per-rule trace).
``build_report`` reshapes that into the public ``RecommendationReport`` — the clean,
display-ready structure with all 12 sections and a fully-populated drug card for every
option. No clinical logic lives here; it only formats what the engine produced.

The internal three categories are mapped to four display buckets: a
``relatively_unsuitable`` item whose ``forced_unsuitable`` flag is set (a rule called
``mark_unsuitable``) is surfaced under ``contraindicated_or_avoid`` instead.
"""
from __future__ import annotations

from typing import Dict, List

from app.engine.context import build_context
from app.engine.ips_rules import ips_reference_entries
from app.engine.registry import get_module
from app.knowledge_base import load_drugs, load_references
from app.models import (
    CaseSummary,
    DrugOption,
    GuidelineReference,
    PatientProfile,
    RecommendationItem,
    RecommendationReport,
)
from app.rules_engine import generate_recommendations

DOSE_NOTE_PLACEHOLDER = (
    "Dose and titration are not generated by this tool; confirm against the local "
    "formulary and product information."
)

CLINICIAN_OVERRIDE_NOTE = (
    "This is decision support, not a prescription. The ranking is a deterministic "
    "starting point; the responsible clinician may override any category based on the "
    "full assessment, and should document the rationale for doing so."
)


def _dimension_hits(item: RecommendationItem, prefixes: tuple) -> List[str]:
    return [h.detail for h in item.rule_trace if h.rule_id.startswith(prefixes)]


def _side_effects(drug: dict) -> List[str]:
    """Derive key risk areas from the structured flags already in the knowledge base
    (not a fabricated list), plus a placeholder to add a reviewed full profile."""
    se: List[str] = []
    mr = drug.get("metabolic_risk")
    if mr in ("moderate", "high"):
        se.append(f"Metabolic/weight effects (rule entry: {mr} risk)")
    sed = drug.get("sedation")
    if sed in ("moderate", "high"):
        se.append(f"Sedation (rule entry: {sed})")
    qt = drug.get("qt_risk")
    if qt in ("moderate", "high"):
        se.append(f"QT prolongation (rule entry: {qt} risk)")
    if drug.get("overdose_toxicity") == "high":
        se.append("Higher toxicity in overdose (rule entry)")
    se.append("Add psychiatrist-reviewed full adverse-effect profile (placeholder).")
    return se


def _reason_for_category(item: RecommendationItem, display_category: str) -> str:
    if display_category == "most_suitable":
        return "Indicated for this diagnosis and no caution or avoid rule fired for this patient."
    if display_category == "use_with_caution":
        n = len(item.cautions)
        return f"Usable with caution: {n} caution{'s' if n != 1 else ''} apply — see why_caution."
    if display_category == "contraindicated_or_avoid":
        return "An avoid/contraindication rule applies for this patient — see why_unsuitable."
    return f"Lower net suitability (score {item.score}) due to one or more negatives — see why_unsuitable."


def _unique(seq: List[str]) -> List[str]:
    seen, out = set(), []
    for x in seq:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out


def _make_option(item: RecommendationItem, display_category: str, drugs_by_name: Dict[str, dict]) -> DrugOption:
    drug = drugs_by_name.get(item.drug, {})

    preg = _dimension_hits(item, ("PREG-", "LACT-"))
    renal = _dimension_hits(item, ("RENAL-",))
    hepatic = _dimension_hits(item, ("HEPATIC-",))
    geri = _dimension_hits(item, ("GERI-",))
    ped = _dimension_hits(item, ("PED-",))
    ddi = _dimension_hits(item, ("DDI-",))

    is_caution = display_category == "use_with_caution"
    is_negative = display_category in ("relatively_unsuitable", "contraindicated_or_avoid")

    preg_note = f"Pregnancy: {drug.get('pregnancy', 'unknown')}; lactation: {drug.get('lactation', 'unknown')}."
    if preg:
        preg_note += " " + " ".join(preg)
    renal_note = f"Renal: {drug.get('renal', 'standard')}."
    if renal:
        renal_note += " " + " ".join(renal)
    hepatic_note = f"Hepatic: {drug.get('hepatic', 'standard')}."
    if hepatic:
        hepatic_note += " " + " ".join(hepatic)

    refs = _unique([r for h in item.rule_trace for r in h.references])
    if not refs:
        refs = ["Add guideline/drug-reference citation (placeholder)."]

    return DrugOption(
        drug_name=item.drug,
        drug_class=item.class_name,
        suitability_score=item.score,
        category=display_category,
        reason_for_category=_reason_for_category(item, display_category),
        why_suitable=list(item.reasons),
        why_caution=list(item.cautions) if is_caution else [],
        why_unsuitable=list(item.cautions) if is_negative else [],
        dose_note_placeholder=DOSE_NOTE_PLACEHOLDER,
        required_baseline_tests=list(item.baseline_investigations),
        monitoring_required=list(item.monitoring),
        important_side_effects=_side_effects(drug),
        interaction_warnings=ddi,
        pregnancy_lactation_note=preg_note,
        renal_note=renal_note,
        hepatic_note=hepatic_note,
        elderly_note="; ".join(geri),
        child_adolescent_note="; ".join(ped),
        guideline_reference_placeholder=refs,
    )


def _case_summary(ctx, module) -> CaseSummary:
    p = ctx.profile
    dx_display = module.display_name
    bits = [
        f"{p.age}-year-old {ctx.sex}",
        ctx.age_group,
        f"{dx_display.lower()} ({ctx.severity})",
        ctx.care_setting.replace("_", " "),
    ]
    if ctx.pregnant_or_planning:
        bits.append("pregnant/planning")
    if ctx.lactating:
        bits.append("lactating")
    if ctx.renal_impaired:
        bits.append("renal impairment")
    if ctx.hepatic_impaired:
        bits.append("hepatic impairment")
    if ctx.cardiac_disease:
        bits.append("cardiac illness")
    if ctx.seizure_disorder:
        bits.append("seizure disorder")
    if p.suicide_risk:
        bits.append("suicide risk")
    summary_text = ", ".join(bits) + "."

    return CaseSummary(
        summary_text=summary_text,
        age=p.age,
        age_group=ctx.age_group,
        sex=ctx.sex,
        bmi=ctx.bmi,
        diagnosis=ctx.diagnosis,
        diagnosis_display=dx_display,
        diagnosis_subtype=p.diagnosis_subtype,
        severity=ctx.severity,
        care_setting=ctx.care_setting,
        pregnancy_status=ctx.profile.pregnancy_status.value if hasattr(ctx.profile.pregnancy_status, "value") else str(ctx.profile.pregnancy_status),
        lactating=ctx.lactating,
        renal_status=ctx.profile.renal_status.value if hasattr(ctx.profile.renal_status, "value") else str(ctx.profile.renal_status),
        hepatic_status=ctx.profile.hepatic_status.value if hasattr(ctx.profile.hepatic_status, "value") else str(ctx.profile.hepatic_status),
        cardiac_disease=ctx.cardiac_disease,
        seizure_disorder=ctx.seizure_disorder,
        suicide_risk=p.suicide_risk,
        non_adherence_risk=p.non_adherence_risk,
    )


def build_report(profile: PatientProfile, *, extended_rules: bool = True) -> RecommendationReport:
    ctx = build_context(profile, extended_rules=extended_rules)
    module = get_module(ctx.diagnosis)
    result = generate_recommendations(profile, extended_rules=extended_rules)
    drugs_by_name = {d["name"]: d for d in load_drugs()}
    # Combined citation registry: built-in references.json + IPS rule citations, so the
    # guideline_references table resolves IPS rule_ids too.
    refs_table = {**load_references(), **ips_reference_entries()}

    most = [_make_option(i, "most_suitable", drugs_by_name) for i in result.most_suitable]
    caution = [_make_option(i, "use_with_caution", drugs_by_name) for i in result.use_with_caution]
    relatively = [_make_option(i, "relatively_unsuitable", drugs_by_name)
                  for i in result.relatively_unsuitable if not i.forced_unsuitable]
    contraindicated = [_make_option(i, "contraindicated_or_avoid", drugs_by_name)
                       for i in result.relatively_unsuitable if i.forced_unsuitable]

    # Required monitoring = de-duplicated union across the realistically-choosable
    # options (most suitable + use with caution).
    required_monitoring = _unique(
        [m for i in (result.most_suitable + result.use_with_caution) for m in i.monitoring]
    )

    # Guideline references = every rule that fired across all displayed options,
    # resolved against the citation registry (sorted for determinism).
    fired_rule_ids = sorted({h.rule_id
                             for bucket in (result.most_suitable, result.use_with_caution, result.relatively_unsuitable)
                             for i in bucket for h in i.rule_trace})
    guideline_references = []
    for rid in fired_rule_ids:
        entry = refs_table.get(rid)
        if entry:
            guideline_references.append(GuidelineReference(
                rule_id=rid,
                citation=entry.get("citation", ""),
                source_type=entry.get("source_type", ""),
                status=entry.get("status", "placeholder"),
            ))

    return RecommendationReport(
        case_summary=_case_summary(ctx, module),
        red_flags=result.urgent_red_flags,
        most_suitable_options=most,
        use_with_caution=caution,
        relatively_unsuitable=relatively,
        contraindicated_or_avoid=contraindicated,
        missing_investigations=result.missing_information,
        required_monitoring=required_monitoring,
        algorithm_notes=result.general_notes,
        non_pharmacological_recommendations=module.non_pharmacological(ctx),
        guideline_references=guideline_references,
        clinician_override_note=CLINICIAN_OVERRIDE_NOTE,
        disclaimer=result.disclaimer,
    )
